// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCMFyfO1k3EY6l-xeqf7rq-NugRD0cCacc',
    appId: '1:333150760216:web:171f6fe8d306e9c8a9c26d',
    messagingSenderId: '333150760216',
    projectId: 'birthday-app-8e4a5',
    authDomain: 'birthday-app-8e4a5.firebaseapp.com',
    storageBucket: 'birthday-app-8e4a5.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCCt17oLNZX9UVjTpxuG0ISwiRPq_4jOe4',
    appId: '1:333150760216:android:fec6748dfcef9611a9c26d',
    messagingSenderId: '333150760216',
    projectId: 'birthday-app-8e4a5',
    storageBucket: 'birthday-app-8e4a5.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAJlbTgSdfCKihcdju4CMoGysayjoQF2xU',
    appId: '1:333150760216:ios:8bc0eecdbb723fcaa9c26d',
    messagingSenderId: '333150760216',
    projectId: 'birthday-app-8e4a5',
    storageBucket: 'birthday-app-8e4a5.firebasestorage.app',
    iosBundleId: 'com.example.someonesTwentyFifthBirthdayFlutter',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAJlbTgSdfCKihcdju4CMoGysayjoQF2xU',
    appId: '1:333150760216:ios:8bc0eecdbb723fcaa9c26d',
    messagingSenderId: '333150760216',
    projectId: 'birthday-app-8e4a5',
    storageBucket: 'birthday-app-8e4a5.firebasestorage.app',
    iosBundleId: 'com.example.someonesTwentyFifthBirthdayFlutter',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCMFyfO1k3EY6l-xeqf7rq-NugRD0cCacc',
    appId: '1:333150760216:web:23b045c97dbf40e6a9c26d',
    messagingSenderId: '333150760216',
    projectId: 'birthday-app-8e4a5',
    authDomain: 'birthday-app-8e4a5.firebaseapp.com',
    storageBucket: 'birthday-app-8e4a5.firebasestorage.app',
  );
}
